name: Run ASTA Scan

on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 * * * 1-5'

jobs:
  run-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance pandas requests

      - name: Run scan.py
        run: python scan.py
